### ISSUE TITLE
Maps.Me coordinates encode

### ISSUE THREAD

**Issue by ghost** [georgjaehnig/mapsme-ge0#1]
Hello! I'm Michael.

I'm searching for a way to encode coordinates in Maps.Me format to create custom links. And there's no information about from Maps.Me at all.
Could you help with that? I checked your decode ge0 URL code and hope you could help me with it.

Thanks a lot!

**Comment by ghost** [comment]
Sorry, I forgot to mention that I work with PHP.

**Comment by georgjaehnig** [comment]
Yeah, this is the PHP function that I ported from:
https://github.com/mapsme/ge0_url_decoder
